version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - npm publish
      - npm run storybook-build
      - aws s3 rm s3://reactimagedropzone.dbroadhurst.net --recursive
      - aws s3 cp .out s3://reactimagedropzone.dbroadhurst.net --recursive --acl public-read

artifacts:
  files:
    build/**/*      